//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;

namespace NewAPI.Models
{
    public class DataModelDbContext : DbContext
    {
        public DataModelDbContext() : base("name=DataModelDbContext")
        {
        }

        public System.Data.Entity.DbSet<NewAPI.Models.QuestionList> QuestionLists { get; set; }
        public System.Data.Entity.DbSet<NewAPI.Models.AnswerList> AnswerLists { get; set; }
        public System.Data.Entity.DbSet<NewAPI.Models.QuestionCheckList> QestionCheckLists { get; set; }
        public object QuestionList { get; internal set; }
    }
}