//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionCheckList
    {
        public int QuestionCheckListID { get; set; }
        public string QuestionCheck1 { get; set; }
        public string QuestionCheck2 { get; set; }
        public string QuestionCheck3 { get; set; }
        public string QuestionCheck4 { get; set; }
        public Nullable<int> QuestionId { get; set; }
    
        public virtual QuestionList QuestionList { get; set; }
    }
}
